[github]
# Register the app here: https://github.com/settings/applications/new
client_id = "{}"
client_secret = "{}"
# filter_by_orgs="{}"
# orgs="{}"

[sqlalchemy]
database_url = "{}"

[session]
secret = "{}"
https_only = {}
